### ISSUE TITLE
Redis Subscription doesnt work with test browser (Mocha)

### ISSUE THREAD

**Issue by pratikfromaspire** [Two-Screen/redis-pubsub#1]
fs.syncExists method results "undefined" from binding.js when try to use is with gulp test-browser of task Mocha.js. 

All the methods of fs module is not available using gulp test-browser. 

We are using Node.js 0.12.7

here is the git link for your reference. https://github.com/aspiresoftware/translation-manager-client-app

We are in urgent need of solution. Quick inputs would be of great help.

**Comment by stephank** [comment]
This is very vague, but sounds like you're trying to use redis-pubsub in a browser (or browser-like test runner) environment. That's not going to work, a browser client cannot (and should not) connect to a redis server directly.

**Comment by stephank** [comment]
I'm closing this, because I believe it's not an issue with redis-pubsub. Reopen with more info if that's not the case.
